name: Publish immutable action
on:
  push:
    tags: ['v*']
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: publish
        uses: actions/publish-immutable-action@4bc8754ffc40f27910afb20287dbbbb675a4e978
